upgrade psycopg2 to stable release 2.7.3.2
This is to fix travis failing due to postgres 10.1 being installed.
```
Collecting psycopg2==2.6.1 (from -r requirements.txt (line 28))
  Downloading psycopg2-2.6.1.tar.gz (371kB)
    100% |████████���███████████████████████| 378kB 3.5MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.1'
```