fix coercing of error message
Error:
```
  File "D4S2/ownership/views.py", line 84, in accept_project_redirect
    '&warning_message=' + warning_message)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Change: Return an empty string instead of None.